# Generated by Django 4.0.4 on 2022-04-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('addresse', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=20)),
                ('teleplone', models.CharField(max_length=30)),
            ],
        ),
    ]
